### ISSUE TITLE
undefined reference to `cngdb_abi_resume`

### ISSUE THREAD

**Issue by Rhythmicc** [Cambricon/CN-GDB#4]
在执行`build.sh`时，遇到如下报错
```shell
infrun.o: In function `process_event_stop_test':
infrun.c:(.text+0x9549): undefined reference to `cngdb_abi_resume'
infrun.c:(.text+0x9595): undefined reference to `cngdb_abi_resume'
collect2: error: ld returned 1 exit status
```
请问是我的环境配置问题吗？

**Comment by kurikomoe** [comment]
编译需要 `libcngdb_backend.so` 这个私有的 lib。和硬件相关的 api 调用位于这个 lib 内，包括不限于 `cngdb_abi_xxx` 等 api。
本仓库只包含与硬件细节无关的上层 GDB 逻辑部分和数据处理部分。

P.S 1. 如果只是想编译通过，可以自行构造空的api函数链接即可。
P.S 2. 这个也是 CUDA-GDB 的做法，通过动态链接库和 RPC 来解耦 GNU GPL 代码和其他硬件细节代码。
